---
:name: Демо TemSys
:tagline: легко управлять сайтом
:domain: temsys.ru
:email: info@temsys.ru
:email_for_form: info@temsys.ru
:phone: "(473)203-03-73"
:phone1: "(473)203-03-73"
:additional_phones: "(473)203-03-74\r\n(473)203-03-75"
:address: ''
:lat:
:lgt:
